package synergyfinalsproject;


import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Ken Computer
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form HMS_Register
     */
    public Registration() {
        initComponents();
        
        Image image = new ImageIcon(this.getClass().getResource("Synergy (Resized Logo).jpg")).getImage();
        this.setIconImage(image);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whitePanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newBluePanel = new javax.swing.JPanel();
        L_createAccount = new javax.swing.JLabel();
        L_backIcon = new javax.swing.JLabel();
        L_firstName = new javax.swing.JLabel();
        TF_firstName = new javax.swing.JTextField();
        L_lastName = new javax.swing.JLabel();
        TF_lastName = new javax.swing.JTextField();
        L_email = new javax.swing.JLabel();
        TF_email = new javax.swing.JTextField();
        L_password = new javax.swing.JLabel();
        TF_password = new javax.swing.JPasswordField();
        L_cPassword = new javax.swing.JLabel();
        TF_cPassword = new javax.swing.JPasswordField();
        L_phoneNum = new javax.swing.JLabel();
        TF_phoneNum = new javax.swing.JTextField();
        L_address = new javax.swing.JLabel();
        TF_address = new javax.swing.JTextField();
        L_gender = new javax.swing.JLabel();
        TF_gender = new javax.swing.JComboBox<>();
        L_birth = new javax.swing.JLabel();
        TF_birth = new javax.swing.JTextField();
        L_role = new javax.swing.JLabel();
        TF_roles = new javax.swing.JComboBox<>();
        L_department = new javax.swing.JLabel();
        TF_department = new javax.swing.JComboBox<>();
        TermsConditions = new javax.swing.JCheckBox();
        B_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Synergy: Create Account");
        setResizable(false);

        whitePanel.setBackground(new java.awt.Color(255, 255, 255));
        whitePanel.setPreferredSize(new java.awt.Dimension(772, 417));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/Synergy (Resized Logo).jpg"))); // NOI18N

        title.setFont(new java.awt.Font("Jomhuria", 0, 70)); // NOI18N
        title.setForeground(new java.awt.Color(21, 41, 157));
        title.setText("Synergy");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        newBluePanel.setBackground(new java.awt.Color(21, 41, 157));

        L_createAccount.setFont(new java.awt.Font("Karma", 1, 27)); // NOI18N
        L_createAccount.setForeground(new java.awt.Color(211, 211, 17));
        L_createAccount.setText("Create Account");

        L_backIcon.setBackground(new java.awt.Color(0, 0, 0));
        L_backIcon.setFont(new java.awt.Font("Karla", 1, 40)); // NOI18N
        L_backIcon.setForeground(new java.awt.Color(255, 255, 255));
        L_backIcon.setText("<");
        L_backIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_backIconMouseClicked(evt);
            }
        });

        L_firstName.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_firstName.setForeground(new java.awt.Color(255, 255, 255));
        L_firstName.setText("First Name:");

        TF_firstName.setBackground(new java.awt.Color(255, 255, 255));
        TF_firstName.setForeground(new java.awt.Color(255, 255, 255));

        L_lastName.setBackground(new java.awt.Color(0, 0, 0));
        L_lastName.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_lastName.setForeground(new java.awt.Color(255, 255, 255));
        L_lastName.setText("Last Name:");

        TF_lastName.setBackground(new java.awt.Color(255, 255, 255));

        L_email.setBackground(new java.awt.Color(0, 0, 0));
        L_email.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_email.setForeground(new java.awt.Color(255, 255, 255));
        L_email.setText("Email:");

        TF_email.setBackground(new java.awt.Color(255, 255, 255));

        L_password.setBackground(new java.awt.Color(0, 0, 0));
        L_password.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_password.setForeground(new java.awt.Color(255, 255, 255));
        L_password.setText("Password:");

        TF_password.setBackground(new java.awt.Color(255, 255, 255));

        L_cPassword.setBackground(new java.awt.Color(0, 0, 0));
        L_cPassword.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_cPassword.setForeground(new java.awt.Color(255, 255, 255));
        L_cPassword.setText("Confirmed Password:");

        TF_cPassword.setBackground(new java.awt.Color(255, 255, 255));

        L_phoneNum.setBackground(new java.awt.Color(0, 0, 0));
        L_phoneNum.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_phoneNum.setForeground(new java.awt.Color(255, 255, 255));
        L_phoneNum.setText("Phone Number:");

        TF_phoneNum.setBackground(new java.awt.Color(255, 255, 255));

        L_address.setBackground(new java.awt.Color(0, 0, 0));
        L_address.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_address.setForeground(new java.awt.Color(255, 255, 255));
        L_address.setText("Address:");

        TF_address.setBackground(new java.awt.Color(255, 255, 255));

        L_gender.setBackground(new java.awt.Color(0, 0, 0));
        L_gender.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_gender.setForeground(new java.awt.Color(255, 255, 255));
        L_gender.setText("Gender:");

        TF_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other"}));
        TF_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_genderActionPerformed(evt);
            }
        });

        L_birth.setBackground(new java.awt.Color(0, 0, 0));
        L_birth.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_birth.setForeground(new java.awt.Color(255, 255, 255));
        L_birth.setText("Date of Birth:");

        TF_birth.setBackground(new java.awt.Color(255, 255, 255));

        L_role.setBackground(new java.awt.Color(0, 0, 0));
        L_role.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_role.setForeground(new java.awt.Color(255, 255, 255));
        L_role.setText("Role:");

        TF_roles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Role #1", "Role #2", "Role #3"}));
        TF_roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_rolesActionPerformed(evt);
            }
        });

        L_department.setBackground(new java.awt.Color(0, 0, 0));
        L_department.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_department.setForeground(new java.awt.Color(255, 255, 255));
        L_department.setText("Department:");

        TF_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department #1", "Department #2", "Department #3"}));
        TF_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_departmentActionPerformed(evt);
            }
        });

        TermsConditions.setFont(new java.awt.Font("Karma", 1, 14)); // NOI18N
        TermsConditions.setForeground(new java.awt.Color(255, 255, 255));
        TermsConditions.setText("I agree to the terms and conditions");
        TermsConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TermsConditionsActionPerformed(evt);
            }
        });

        B_register.setFont(new java.awt.Font("Karma", 1, 12)); // NOI18N
        B_register.setText("Register");
        B_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newBluePanelLayout = new javax.swing.GroupLayout(newBluePanel);
        newBluePanel.setLayout(newBluePanelLayout);
        newBluePanelLayout.setHorizontalGroup(
            newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBluePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_createAccount)
                .addGap(113, 113, 113)
                .addComponent(L_backIcon)
                .addGap(30, 30, 30))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_register)
                    .addComponent(TermsConditions)
                    .addComponent(TF_department, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_department)
                    .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TF_roles, 0, 345, Short.MAX_VALUE)
                        .addComponent(L_role)
                        .addComponent(TF_birth)
                        .addComponent(L_birth)
                        .addComponent(TF_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_gender)
                        .addComponent(TF_address)
                        .addComponent(L_address)
                        .addComponent(TF_phoneNum)
                        .addComponent(L_phoneNum)
                        .addComponent(TF_cPassword)
                        .addComponent(L_cPassword)
                        .addComponent(TF_password)
                        .addComponent(L_password)
                        .addComponent(TF_email)
                        .addComponent(L_email)
                        .addComponent(TF_lastName)
                        .addComponent(L_lastName)
                        .addComponent(TF_firstName)
                        .addComponent(L_firstName)))
                .addGap(0, 91, Short.MAX_VALUE))
        );
        newBluePanelLayout.setVerticalGroup(
            newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_backIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_createAccount))
                .addGap(18, 18, 18)
                .addComponent(L_firstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_lastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_cPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_cPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_phoneNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_birth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_role)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_roles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_department)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TermsConditions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_register)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(newBluePanel);

        javax.swing.GroupLayout whitePanelLayout = new javax.swing.GroupLayout(whitePanel);
        whitePanel.setLayout(whitePanelLayout);
        whitePanelLayout.setHorizontalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(whitePanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(title))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        whitePanelLayout.setVerticalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitePanelLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_registerActionPerformed

        // Object to setVisibility and append displayError specific Messages
        Error_Display errorMSG = new Error_Display();
        //Total amount of errors to be checked by the program: [7]
        
        //-------------------------------------------------------------------------------------------
        
        if (TF_firstName.getText().isEmpty()) {
            errorMSG.setVisible(true);
            errorMSG.displayError.append("Empty TextField Error: \nOne or More TextField is Empty.");
        } else if (TF_lastName.getText().isEmpty()) {
            errorMSG.setVisible(true);
            errorMSG.displayError.append("Empty TextField Error: \nOne or More TextField is Empty.");
        } else if (TF_email.getText().isEmpty()) {
            errorMSG.setVisible(true);
            errorMSG.displayError.append("Empty TextField Error: \nOne or More TextField is Empty.");
        } else if (TF_password.getText().isEmpty()) {
            errorMSG.setVisible(true);
            errorMSG.displayError.append("Empty TextField Error: \nOne or More TextField is Empty.");
        } else if (TF_cPassword.getText().isEmpty()) {
            errorMSG.setVisible(true);
            errorMSG.displayError.append("Empty TextField Error: \nOne or More TextField is Empty.");
        } else if (TF_phoneNum.getText().isEmpty()) {
            errorMSG.setVisible(true);
            errorMSG.displayError.append("Empty TextField Error: \nOne or More TextField is Empty.");
        } else if (TF_address.getText().isEmpty()) {
            errorMSG.setVisible(true);
            errorMSG.displayError.append("Empty TextField Error: \nOne or More TextField is Empty.");
        } else if (TF_birth.getText().isEmpty()) {
            errorMSG.setVisible(true);
            errorMSG.displayError.append("Empty TextField Error: \nOne or More TextField is Empty.");

        } else {

            if (!TF_password.getText().equals(TF_cPassword.getText())) {
                errorMSG.setVisible(true);
                errorMSG.displayError.append("Mismatch Password Error: \nPassword and Confirmed Password do NOT match.");

            } else {

                if (!TF_password.getText().matches(".*[a-zA-Z].*") || !TF_password.getText().matches(".*\\d.*") || !TF_password.getText().matches(".*[^a-zA-Z\\d].*")) {
                    errorMSG.setVisible(true);
                    errorMSG.displayError.append("Missing Symbol and/or Number Error: \nPassword requires atleast ONE Symbol and ONE Number.");

                } else {

                    if (TF_password.getText().length() <= 5) { // [4]
                        errorMSG.setVisible(true);
                        errorMSG.displayError.append("Passowrd Length Error: \nPassword must atleast have 6 characters.");

                    } else {

                        if (TF_phoneNum.getText().matches(".*[a-zA-Z].*") || TF_phoneNum.getText().matches(".*[^\\d].*")) {
                            errorMSG.setVisible(true);
                            errorMSG.displayError.append("Phone Number Letter and/or Symbol Error: \nPhone Number TextField has a Letter and/or Number in it.");

                        } else {

                            if (TF_phoneNum.getText().length() != 11) {
                                errorMSG.setVisible(true);
                                errorMSG.displayError.append("Phone Number Length Error: \nPhone Number must have and should be equal to 11 digits.");

                            } else {

                                if (!TermsConditions.isSelected()) {
                                    errorMSG.setVisible(true);
                                    errorMSG.displayError.append("TOC unchecked Error: \nTerms And Condition Must be checked before you can create an account.");

                                } else {

                                    System.out.println("Program Successful"); // Temporary SysOut code for checking..
                                    // enter code here to open another JFrame..

                                }

                            }

                        }

                    }

                }

            }

        }
    }//GEN-LAST:event_B_registerActionPerformed

    private void TermsConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TermsConditionsActionPerformed

    }//GEN-LAST:event_TermsConditionsActionPerformed

    private void TF_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_departmentActionPerformed

    private void TF_rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_rolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_rolesActionPerformed

    private void TF_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_genderActionPerformed

    private void L_backIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_backIconMouseClicked
        
        System.out.println("Redirecting To..");
        //Enter code here to open another JFrame..
        
    }//GEN-LAST:event_L_backIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_register;
    private javax.swing.JLabel L_address;
    private javax.swing.JLabel L_backIcon;
    private javax.swing.JLabel L_birth;
    private javax.swing.JLabel L_cPassword;
    private javax.swing.JLabel L_createAccount;
    private javax.swing.JLabel L_department;
    private javax.swing.JLabel L_email;
    private javax.swing.JLabel L_firstName;
    private javax.swing.JLabel L_gender;
    private javax.swing.JLabel L_lastName;
    private javax.swing.JLabel L_password;
    private javax.swing.JLabel L_phoneNum;
    private javax.swing.JLabel L_role;
    private javax.swing.JTextField TF_address;
    private javax.swing.JTextField TF_birth;
    private javax.swing.JPasswordField TF_cPassword;
    private javax.swing.JComboBox<String> TF_department;
    private javax.swing.JTextField TF_email;
    private javax.swing.JTextField TF_firstName;
    private javax.swing.JComboBox<String> TF_gender;
    private javax.swing.JTextField TF_lastName;
    private javax.swing.JPasswordField TF_password;
    private javax.swing.JTextField TF_phoneNum;
    private javax.swing.JComboBox<String> TF_roles;
    private javax.swing.JCheckBox TermsConditions;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel newBluePanel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel whitePanel;
    // End of variables declaration//GEN-END:variables
}
