/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package synergyfinalsproject;

/**
 *
 * @author Test
 */
public class Synergy_SetSchedule extends javax.swing.JFrame {

    /**
     * Creates new form Synergy_SetSchedule
     */
    public Synergy_SetSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_ASSIGNED = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TF_TIME1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(217, 217, 21));
        jLabel6.setFont(new java.awt.Font("Karma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 108, 108));
        jLabel6.setText("Assigned Physician");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 100, 230, 40);

        jLabel7.setFont(new java.awt.Font("Karma", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(6, 61, 134));
        jLabel7.setText("Set Schedule of Appointment");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 300, 40);
        jPanel1.add(TF_ASSIGNED);
        TF_ASSIGNED.setBounds(10, 130, 210, 22);

        jLabel8.setBackground(new java.awt.Color(217, 217, 21));
        jLabel8.setFont(new java.awt.Font("Karma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 108, 108));
        jLabel8.setText("Time: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 40, 300, 40);
        jPanel1.add(TF_TIME1);
        TF_TIME1.setBounds(10, 70, 210, 22);

        jButton1.setText("Set");
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 180, 210, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Synergy_SetSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Synergy_SetSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Synergy_SetSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Synergy_SetSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Synergy_SetSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_ASSIGNED;
    private javax.swing.JTextField TF_TIME1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
