/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package synergyfinalsproject;

import javax.swing.JFrame;

/**
 *
 * @author Test
 */
public class Synergy_SettingsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Synergy_SettingsAdmin
     */
    public Synergy_SettingsAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        L_firstName25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        L_firstName24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        L_firstName22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PatientAbout = new javax.swing.JButton();
        PatientSettings = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        HomeButon = new javax.swing.JButton();
        SideMenuu = new javax.swing.JLabel();
        WholeBackground = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        L_firstName23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(130, 200, 300, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(130, 130, 300, 20);

        L_firstName25.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName25.setFont(new java.awt.Font("Karma", 1, 15)); // NOI18N
        L_firstName25.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName25.setText("Email Recovery");
        jPanel1.add(L_firstName25);
        L_firstName25.setBounds(130, 170, 180, 30);

        jButton2.setFont(new java.awt.Font("Karma Light", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(6, 61, 134));
        jButton2.setText("Change Password");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 320, 300, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(130, 270, 300, 20);

        L_firstName24.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName24.setFont(new java.awt.Font("Karma", 1, 15)); // NOI18N
        L_firstName24.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName24.setText("Admin Password");
        jPanel1.add(L_firstName24);
        L_firstName24.setBounds(130, 240, 180, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 130, 300, 20);

        L_firstName22.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName22.setFont(new java.awt.Font("Karma", 1, 15)); // NOI18N
        L_firstName22.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName22.setText("Admin Username");
        jPanel1.add(L_firstName22);
        L_firstName22.setBounds(130, 100, 180, 30);

        jLabel4.setFont(new java.awt.Font("Karma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 61, 134));
        jLabel4.setText("Settings");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 40, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/BigBackgound (1).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 50, 520, 350);

        PatientAbout.setBackground(new java.awt.Color(221, 238, 249));
        PatientAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newInfo (1).png"))); // NOI18N
        PatientAbout.setBorder(null);
        PatientAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAboutActionPerformed(evt);
            }
        });
        jPanel1.add(PatientAbout);
        PatientAbout.setBounds(30, 220, 30, 30);

        PatientSettings.setBackground(new java.awt.Color(221, 238, 249));
        PatientSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newGear (2).png"))); // NOI18N
        PatientSettings.setBorder(null);
        PatientSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientSettingsActionPerformed(evt);
            }
        });
        jPanel1.add(PatientSettings);
        PatientSettings.setBounds(30, 150, 30, 30);

        LogOut.setBackground(new java.awt.Color(221, 238, 249));
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newLogOuy (1).png"))); // NOI18N
        LogOut.setBorder(null);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut);
        LogOut.setBounds(30, 290, 30, 30);

        HomeButon.setBackground(new java.awt.Color(221, 238, 249));
        HomeButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newHome (1).png"))); // NOI18N
        HomeButon.setBorder(null);
        HomeButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeButon);
        HomeButon.setBounds(30, 90, 30, 30);

        SideMenuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/Side Menu (2).png"))); // NOI18N
        SideMenuu.setMaximumSize(new java.awt.Dimension(50, 313));
        jPanel1.add(SideMenuu);
        SideMenuu.setBounds(20, 0, 60, 420);

        WholeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/backgroundblue (1).png"))); // NOI18N
        jPanel1.add(WholeBackground);
        WholeBackground.setBounds(80, 10, 772, 400);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(440, 110, 260, 20);

        L_firstName23.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName23.setFont(new java.awt.Font("Karma", 1, 15)); // NOI18N
        L_firstName23.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName23.setText("Password");
        jPanel1.add(L_firstName23);
        L_firstName23.setBounds(580, 90, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAboutActionPerformed
        dispose();
        JFrame info = new Synergy_AdminInfo();
        info.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        info.setVisible(true);
    }//GEN-LAST:event_PatientAboutActionPerformed

    private void PatientSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientSettingsActionPerformed
        dispose();
        JFrame settings = new Synergy_SettingsAdmin();
        settings.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        settings.setVisible(true);
    }//GEN-LAST:event_PatientSettingsActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        dispose();
        JFrame login = new Synergy_LogIn();
        login.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        login.setVisible(true);

    }//GEN-LAST:event_LogOutActionPerformed

    private void HomeButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButonActionPerformed
        dispose();
        JFrame home = new Synergy_HomeAdmin();
        home.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        home.setVisible(true);
    }//GEN-LAST:event_HomeButonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Synergy_SettingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Synergy_SettingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Synergy_SettingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Synergy_SettingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Synergy_SettingsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButon;
    private javax.swing.JLabel L_firstName22;
    private javax.swing.JLabel L_firstName23;
    private javax.swing.JLabel L_firstName24;
    private javax.swing.JLabel L_firstName25;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton PatientAbout;
    private javax.swing.JButton PatientSettings;
    private javax.swing.JLabel SideMenuu;
    private javax.swing.JLabel WholeBackground;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
