/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package synergyfinalsproject;

import javax.swing.JFrame;

/**
 *
 * @author Test
 */
public class Synergy_PendingAppointment extends javax.swing.JFrame {

    /**
     * Creates new form Synergy_Appointmentt
     */
    public Synergy_PendingAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        L_firstName22 = new javax.swing.JLabel();
        TF_AppoYear = new javax.swing.JTextField();
        TF_AppoMonth1 = new javax.swing.JTextField();
        L_firstName24 = new javax.swing.JLabel();
        TF_AppoDay = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        L_firstName25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        L_firstName23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        L_firstName26 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        L_firstName27 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        L_firstName28 = new javax.swing.JLabel();
        L_firstName29 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        L_firstName30 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        L_firstName31 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        L_firstName6 = new javax.swing.JLabel();
        L_firstName7 = new javax.swing.JLabel();
        TF_initial = new javax.swing.JTextField();
        L_firstName8 = new javax.swing.JLabel();
        TF_Lname1 = new javax.swing.JTextField();
        L_firstName9 = new javax.swing.JLabel();
        L_firstName10 = new javax.swing.JLabel();
        TF_Fname2 = new javax.swing.JTextField();
        L_firstName11 = new javax.swing.JLabel();
        TF_emailAd = new javax.swing.JTextField();
        L_firstName12 = new javax.swing.JLabel();
        L_firstName13 = new javax.swing.JLabel();
        L_firstName14 = new javax.swing.JLabel();
        TF_MaritalStatus = new javax.swing.JTextField();
        L_firstName15 = new javax.swing.JLabel();
        TF_EmergencyContact = new javax.swing.JTextField();
        L_firstName16 = new javax.swing.JLabel();
        TF_address2 = new javax.swing.JTextField();
        L_firstName17 = new javax.swing.JLabel();
        L_firstName18 = new javax.swing.JLabel();
        TF_phoneNum1 = new javax.swing.JTextField();
        L_firstName19 = new javax.swing.JLabel();
        TF_RStoPatient = new javax.swing.JTextField();
        L_firstName20 = new javax.swing.JLabel();
        TF_EmergencyName2 = new javax.swing.JTextField();
        L_firstName21 = new javax.swing.JLabel();
        TF_EmergencyContact1 = new javax.swing.JTextField();
        TF_Birthdate = new javax.swing.JTextField();
        TF_Gender1 = new javax.swing.JTextField();
        TF_EmergencyAddress1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        PatientAbout = new javax.swing.JButton();
        HomeButon = new javax.swing.JButton();
        PatientSettings = new javax.swing.JButton();
        SideMenuu = new javax.swing.JLabel();
        WholeBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Karma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(6, 61, 134));
        jLabel6.setText("Schedule");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 0, 140, 40);

        L_firstName22.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName22.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName22.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName22.setText("Year");
        jPanel3.add(L_firstName22);
        L_firstName22.setBounds(10, 140, 40, 20);

        TF_AppoYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_AppoYearActionPerformed(evt);
            }
        });
        jPanel3.add(TF_AppoYear);
        TF_AppoYear.setBounds(10, 160, 111, 20);

        TF_AppoMonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_AppoMonth1ActionPerformed(evt);
            }
        });
        jPanel3.add(TF_AppoMonth1);
        TF_AppoMonth1.setBounds(10, 60, 111, 20);

        L_firstName24.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName24.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName24.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName24.setText("Day");
        jPanel3.add(L_firstName24);
        L_firstName24.setBounds(10, 90, 40, 20);

        TF_AppoDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_AppoDayActionPerformed(evt);
            }
        });
        jPanel3.add(TF_AppoDay);
        TF_AppoDay.setBounds(10, 110, 111, 20);

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel3.add(Cancel);
        Cancel.setBounds(0, 200, 70, 23);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel3.add(Save);
        Save.setBounds(70, 200, 60, 23);

        L_firstName25.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName25.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName25.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName25.setText("Month");
        jPanel3.add(L_firstName25);
        L_firstName25.setBounds(10, 40, 40, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(580, 70, 130, 290);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        L_firstName23.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName23.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName23.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName23.setText("Progress note");

        jTextField1.setEnabled(false);

        L_firstName26.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName26.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName26.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName26.setText("Time");

        jTextField2.setEnabled(false);

        L_firstName27.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName27.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName27.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName27.setText("Diagnosis");

        jTextField3.setEnabled(false);

        L_firstName28.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName28.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName28.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName28.setText("Prescribed Medicine:");

        L_firstName29.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName29.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName29.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName29.setText("Diagnosis");

        jTextField5.setEnabled(false);

        L_firstName30.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName30.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName30.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName30.setText("Birthdate");

        jTextField6.setEnabled(false);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setEnabled(false);
        jScrollPane2.setViewportView(jList1);

        L_firstName31.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName31.setFont(new java.awt.Font("Karma", 1, 13)); // NOI18N
        L_firstName31.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName31.setText("Type of Appointment");

        jTextField4.setActionCommand("<Not Set>");
        jTextField4.setDragEnabled(true);
        jTextField4.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(L_firstName27)
                        .addGap(173, 173, 173)
                        .addComponent(L_firstName29))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(L_firstName30)
                        .addGap(63, 63, 63)
                        .addComponent(L_firstName26)
                        .addGap(79, 79, 79)
                        .addComponent(L_firstName31, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(L_firstName28, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(L_firstName23, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane3.setViewportView(jPanel4);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(100, 220, 460, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/setAppointment (1).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(570, 40, 190, 350);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);

        L_firstName6.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName6.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName6.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName6.setText("Marital Status:");

        L_firstName7.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName7.setFont(new java.awt.Font("Karma", 1, 15)); // NOI18N
        L_firstName7.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName7.setText("Emergency Contact Information");

        L_firstName8.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName8.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName8.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName8.setText("Middle Initial:");

        L_firstName9.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName9.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName9.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName9.setText("Last Name: ");

        L_firstName10.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName10.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName10.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName10.setText("First Name: ");

        L_firstName11.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName11.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName11.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName11.setText("Email:");

        TF_emailAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_emailAdActionPerformed(evt);
            }
        });

        L_firstName12.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName12.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName12.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName12.setText("Sex:");

        L_firstName13.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName13.setFont(new java.awt.Font("Karma", 1, 15)); // NOI18N
        L_firstName13.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName13.setText("Personal Information");

        L_firstName14.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName14.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName14.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName14.setText("Contact Number:");

        L_firstName15.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName15.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName15.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName15.setText("Contact Number");

        TF_EmergencyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EmergencyContactActionPerformed(evt);
            }
        });

        L_firstName16.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName16.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName16.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName16.setText("Address:");

        TF_address2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_address2ActionPerformed(evt);
            }
        });

        L_firstName17.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName17.setFont(new java.awt.Font("Karma", 1, 15)); // NOI18N
        L_firstName17.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName17.setText("Contact Information");

        L_firstName18.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName18.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName18.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName18.setText("Birthdate: ");

        TF_phoneNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_phoneNum1ActionPerformed(evt);
            }
        });

        L_firstName19.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName19.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName19.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName19.setText("Relationship to the patient: ");

        TF_RStoPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_RStoPatientActionPerformed(evt);
            }
        });

        L_firstName20.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName20.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName20.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName20.setText("Name:");

        TF_EmergencyName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EmergencyName2ActionPerformed(evt);
            }
        });

        L_firstName21.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName21.setFont(new java.awt.Font("Karma", 1, 10)); // NOI18N
        L_firstName21.setForeground(new java.awt.Color(108, 108, 108));
        L_firstName21.setText("Address: ");

        TF_EmergencyContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EmergencyContact1ActionPerformed(evt);
            }
        });

        TF_EmergencyAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EmergencyAddress1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(L_firstName10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(L_firstName9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(L_firstName8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TF_Fname2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TF_Lname1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TF_initial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(L_firstName18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(L_firstName12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(L_firstName6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TF_Birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TF_Gender1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TF_MaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(L_firstName17, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(L_firstName16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(L_firstName11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TF_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TF_emailAd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(L_firstName15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_phoneNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(L_firstName20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(L_firstName14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TF_EmergencyName2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_EmergencyContact1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_EmergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(L_firstName21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(L_firstName19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TF_EmergencyAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TF_RStoPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(L_firstName13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Fname2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Lname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_initial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Gender1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_MaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(L_firstName17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_emailAd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(L_firstName15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TF_phoneNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(L_firstName7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_EmergencyName2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_EmergencyContact1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_EmergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_firstName19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_EmergencyAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_RStoPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 60, 460, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/personalInfo (1).png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 190, 480, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/personalInfo (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 30, 480, 210);

        LogOut.setBackground(new java.awt.Color(221, 238, 249));
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newLogOuy (1).png"))); // NOI18N
        LogOut.setBorder(null);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut);
        LogOut.setBounds(30, 290, 30, 30);

        PatientAbout.setBackground(new java.awt.Color(221, 238, 249));
        PatientAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newInfo (1).png"))); // NOI18N
        PatientAbout.setBorder(null);
        PatientAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAboutActionPerformed(evt);
            }
        });
        jPanel1.add(PatientAbout);
        PatientAbout.setBounds(30, 220, 30, 30);

        HomeButon.setBackground(new java.awt.Color(221, 238, 249));
        HomeButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newHome (1).png"))); // NOI18N
        HomeButon.setBorder(null);
        HomeButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeButon);
        HomeButon.setBounds(30, 90, 30, 30);

        PatientSettings.setBackground(new java.awt.Color(221, 238, 249));
        PatientSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newGear (2).png"))); // NOI18N
        PatientSettings.setBorder(null);
        PatientSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientSettingsActionPerformed(evt);
            }
        });
        jPanel1.add(PatientSettings);
        PatientSettings.setBounds(30, 150, 30, 30);

        SideMenuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/Side Menu (2).png"))); // NOI18N
        SideMenuu.setMaximumSize(new java.awt.Dimension(50, 313));
        jPanel1.add(SideMenuu);
        SideMenuu.setBounds(20, 0, 60, 420);

        WholeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/backgroundblue (1).png"))); // NOI18N
        jPanel1.add(WholeBackground);
        WholeBackground.setBounds(80, 10, 772, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_AppoYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_AppoYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_AppoYearActionPerformed

    private void TF_AppoMonth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_AppoMonth1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_AppoMonth1ActionPerformed

    private void TF_AppoDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_AppoDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_AppoDayActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void TF_emailAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_emailAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_emailAdActionPerformed

    private void TF_EmergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EmergencyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EmergencyContactActionPerformed

    private void TF_address2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_address2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_address2ActionPerformed

    private void TF_phoneNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_phoneNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_phoneNum1ActionPerformed

    private void TF_RStoPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_RStoPatientActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_RStoPatientActionPerformed

    private void TF_EmergencyName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EmergencyName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EmergencyName2ActionPerformed

    private void TF_EmergencyContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EmergencyContact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EmergencyContact1ActionPerformed

    private void TF_EmergencyAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EmergencyAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EmergencyAddress1ActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        dispose();
        JFrame login = new Synergy_LogIn();
        login.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        login.setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    private void PatientAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAboutActionPerformed
        dispose();
        JFrame home = new Synergy_AdminInfo();
        home.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        home.setVisible(true);
    }//GEN-LAST:event_PatientAboutActionPerformed

    private void HomeButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButonActionPerformed
        dispose();
        JFrame home = new Synergy_HomeAdmin();
        home.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        home.setVisible(true);
    }//GEN-LAST:event_HomeButonActionPerformed

    private void PatientSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientSettingsActionPerformed
        dispose();
        JFrame home = new Synergy_SettingsAdmin();
        home.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        home.setVisible(true);
    }//GEN-LAST:event_PatientSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Synergy_PendingAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Synergy_PendingAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Synergy_PendingAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Synergy_PendingAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Synergy_PendingAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton HomeButon;
    private javax.swing.JLabel L_firstName10;
    private javax.swing.JLabel L_firstName11;
    private javax.swing.JLabel L_firstName12;
    private javax.swing.JLabel L_firstName13;
    private javax.swing.JLabel L_firstName14;
    private javax.swing.JLabel L_firstName15;
    private javax.swing.JLabel L_firstName16;
    private javax.swing.JLabel L_firstName17;
    private javax.swing.JLabel L_firstName18;
    private javax.swing.JLabel L_firstName19;
    private javax.swing.JLabel L_firstName20;
    private javax.swing.JLabel L_firstName21;
    private javax.swing.JLabel L_firstName22;
    private javax.swing.JLabel L_firstName23;
    private javax.swing.JLabel L_firstName24;
    private javax.swing.JLabel L_firstName25;
    private javax.swing.JLabel L_firstName26;
    private javax.swing.JLabel L_firstName27;
    private javax.swing.JLabel L_firstName28;
    private javax.swing.JLabel L_firstName29;
    private javax.swing.JLabel L_firstName30;
    private javax.swing.JLabel L_firstName31;
    private javax.swing.JLabel L_firstName6;
    private javax.swing.JLabel L_firstName7;
    private javax.swing.JLabel L_firstName8;
    private javax.swing.JLabel L_firstName9;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton PatientAbout;
    private javax.swing.JButton PatientSettings;
    private javax.swing.JButton Save;
    private javax.swing.JLabel SideMenuu;
    private javax.swing.JTextField TF_AppoDay;
    private javax.swing.JTextField TF_AppoMonth1;
    private javax.swing.JTextField TF_AppoYear;
    private javax.swing.JTextField TF_Birthdate;
    private javax.swing.JTextField TF_EmergencyAddress1;
    private javax.swing.JTextField TF_EmergencyContact;
    private javax.swing.JTextField TF_EmergencyContact1;
    private javax.swing.JTextField TF_EmergencyName2;
    private javax.swing.JTextField TF_Fname2;
    private javax.swing.JTextField TF_Gender1;
    private javax.swing.JTextField TF_Lname1;
    private javax.swing.JTextField TF_MaritalStatus;
    private javax.swing.JTextField TF_RStoPatient;
    private javax.swing.JTextField TF_address2;
    private javax.swing.JTextField TF_emailAd;
    private javax.swing.JTextField TF_initial;
    private javax.swing.JTextField TF_phoneNum1;
    private javax.swing.JLabel WholeBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
