/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package synergyfinalsproject;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Test
 */
public class Synergy_Registration extends javax.swing.JFrame {

    /**
     * Creates new form Synergy_Registration
     */
    public Synergy_Registration() {
        initComponents();
        
        Image image = new ImageIcon(this.getClass().getResource("Synergy (Resized Logo).jpg")).getImage();
        this.setIconImage(image);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whitePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newBluePanel = new javax.swing.JPanel();
        L_firstName = new javax.swing.JLabel();
        L_firstName1 = new javax.swing.JLabel();
        TF_FirstName = new javax.swing.JTextField();
        TF_MiddleName = new javax.swing.JTextField();
        L_firstName3 = new javax.swing.JLabel();
        L_lastName = new javax.swing.JLabel();
        TF_Year = new javax.swing.JTextField();
        L_gender = new javax.swing.JLabel();
        L_lastName1 = new javax.swing.JLabel();
        MaritalStatus = new javax.swing.JComboBox<>();
        TF_month1 = new javax.swing.JTextField();
        TF_day1 = new javax.swing.JTextField();
        L_lastName2 = new javax.swing.JLabel();
        TF_surname2 = new javax.swing.JTextField();
        Gender2 = new javax.swing.JComboBox<>();
        L_lastName3 = new javax.swing.JLabel();
        TF_cPassword = new javax.swing.JTextField();
        L_lastName4 = new javax.swing.JLabel();
        TF_phoneNum = new javax.swing.JTextField();
        L_lastName5 = new javax.swing.JLabel();
        TF_Email1 = new javax.swing.JTextField();
        L_password = new javax.swing.JLabel();
        TF_UserName = new javax.swing.JTextField();
        L_haveAccount = new javax.swing.JLabel();
        TF_password = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        L_password2 = new javax.swing.JLabel();
        L_password3 = new javax.swing.JLabel();
        L_password4 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        L_lastName6 = new javax.swing.JLabel();
        TF_address1 = new javax.swing.JTextField();
        B_register = new javax.swing.JButton();
        TermsConditions = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Synergy: Create Account");

        whitePanel.setBackground(new java.awt.Color(221, 238, 249));
        whitePanel.setPreferredSize(new java.awt.Dimension(772, 417));
        whitePanel.setLayout(null);

        title.setFont(new java.awt.Font("Jomhuria", 0, 70)); // NOI18N
        title.setForeground(new java.awt.Color(21, 41, 157));
        title.setText("Synergy");
        whitePanel.add(title);
        title.setBounds(80, 251, 142, 60);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        newBluePanel.setBackground(new java.awt.Color(221, 238, 249));

        L_firstName.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName.setFont(new java.awt.Font("Karma", 1, 28)); // NOI18N
        L_firstName.setForeground(new java.awt.Color(49, 91, 2));
        L_firstName.setText("Create Account");

        L_firstName1.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName1.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_firstName1.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName1.setText("Middle Name");

        TF_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_FirstNameActionPerformed(evt);
            }
        });

        TF_MiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_MiddleNameActionPerformed(evt);
            }
        });

        L_firstName3.setBackground(new java.awt.Color(0, 0, 0));
        L_firstName3.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_firstName3.setForeground(new java.awt.Color(6, 61, 134));
        L_firstName3.setText("First Name:");

        L_lastName.setBackground(new java.awt.Color(0, 0, 0));
        L_lastName.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_lastName.setForeground(new java.awt.Color(6, 61, 134));
        L_lastName.setText("Status");

        TF_Year.setForeground(new java.awt.Color(102, 102, 102));
        TF_Year.setText("Year");
        TF_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_YearActionPerformed(evt);
            }
        });

        L_gender.setBackground(new java.awt.Color(0, 0, 0));
        L_gender.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_gender.setForeground(new java.awt.Color(6, 61, 134));
        L_gender.setText("Gender:");

        L_lastName1.setBackground(new java.awt.Color(0, 0, 0));
        L_lastName1.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_lastName1.setForeground(new java.awt.Color(6, 61, 134));
        L_lastName1.setText("Contact Number");

        MaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Married", "Single" }));
        MaritalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaritalStatusActionPerformed(evt);
            }
        });

        TF_month1.setForeground(new java.awt.Color(102, 102, 102));
        TF_month1.setText("Month");
        TF_month1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_month1ActionPerformed(evt);
            }
        });

        TF_day1.setForeground(new java.awt.Color(102, 102, 102));
        TF_day1.setText("Day");
        TF_day1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_day1ActionPerformed(evt);
            }
        });

        L_lastName2.setBackground(new java.awt.Color(0, 0, 0));
        L_lastName2.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_lastName2.setForeground(new java.awt.Color(6, 61, 134));
        L_lastName2.setText("Birthdate");

        TF_surname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_surname2ActionPerformed(evt);
            }
        });

        Gender2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select gender", "Male", "Female", "Rather not say" }));
        Gender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gender2ActionPerformed(evt);
            }
        });

        L_lastName3.setBackground(new java.awt.Color(0, 0, 0));
        L_lastName3.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_lastName3.setForeground(new java.awt.Color(6, 61, 134));
        L_lastName3.setText("Surname:");

        L_lastName4.setBackground(new java.awt.Color(0, 0, 0));
        L_lastName4.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_lastName4.setForeground(new java.awt.Color(6, 61, 134));
        L_lastName4.setText("Username");

        TF_phoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_phoneNumActionPerformed(evt);
            }
        });

        L_lastName5.setBackground(new java.awt.Color(0, 0, 0));
        L_lastName5.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_lastName5.setForeground(new java.awt.Color(6, 61, 134));
        L_lastName5.setText("Email");

        TF_Email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Email1ActionPerformed(evt);
            }
        });

        L_password.setBackground(new java.awt.Color(0, 0, 0));
        L_password.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_password.setForeground(new java.awt.Color(6, 61, 134));
        L_password.setText("Confirm Password");

        L_haveAccount.setBackground(new java.awt.Color(0, 0, 0));
        L_haveAccount.setFont(new java.awt.Font("Karma", 1, 16)); // NOI18N
        L_haveAccount.setText("Already have an account?");
        L_haveAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_haveAccountMouseClicked(evt);
            }
        });

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        L_password2.setBackground(new java.awt.Color(0, 0, 0));
        L_password2.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_password2.setForeground(new java.awt.Color(6, 61, 134));
        L_password2.setText("Password:");

        L_password3.setBackground(new java.awt.Color(0, 0, 0));
        L_password3.setFont(new java.awt.Font("Karma", 1, 16)); // NOI18N
        L_password3.setForeground(new java.awt.Color(6, 61, 134));
        L_password3.setText("terms and conditions");

        L_password4.setBackground(new java.awt.Color(0, 0, 0));
        L_password4.setFont(new java.awt.Font("Karma", 1, 16)); // NOI18N
        L_password4.setText("i accept the");

        register.setBackground(new java.awt.Color(49, 91, 2));
        register.setFont(new java.awt.Font("Karma", 0, 14)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        L_lastName6.setBackground(new java.awt.Color(0, 0, 0));
        L_lastName6.setFont(new java.awt.Font("Karma", 1, 18)); // NOI18N
        L_lastName6.setForeground(new java.awt.Color(6, 61, 134));
        L_lastName6.setText("Address");

        javax.swing.GroupLayout newBluePanelLayout = new javax.swing.GroupLayout(newBluePanel);
        newBluePanel.setLayout(newBluePanelLayout);
        newBluePanelLayout.setHorizontalGroup(
            newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(L_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(L_firstName3)
                .addGap(104, 104, 104)
                .addComponent(L_firstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TF_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(TF_MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(L_lastName3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(L_gender))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TF_surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Gender2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(L_lastName2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(L_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TF_month1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(TF_day1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(TF_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(MaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(L_lastName5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(L_lastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TF_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(TF_phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(L_lastName6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TF_address1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(L_lastName4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TF_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(L_password2)
                .addGap(128, 128, 128)
                .addComponent(L_password, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TF_password, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TF_cPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(L_password4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(L_password3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(L_haveAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        newBluePanelLayout.setVerticalGroup(
            newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBluePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(L_firstName)
                .addGap(13, 13, 13)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_firstName3)
                    .addComponent(L_firstName1))
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_lastName3)
                    .addComponent(L_gender))
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_surname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_lastName2)
                    .addComponent(L_lastName))
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_day1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_lastName5)
                    .addComponent(L_lastName1))
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(L_lastName6)
                .addGap(0, 0, 0)
                .addComponent(TF_address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L_lastName4)
                .addGap(0, 0, 0)
                .addComponent(TF_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_password, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_cPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(newBluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(L_password4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_password3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(L_haveAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(register))
        );

        jScrollPane2.setViewportView(newBluePanel);

        whitePanel.add(jScrollPane2);
        jScrollPane2.setBounds(300, 0, 470, 410);

        B_register.setFont(new java.awt.Font("Karma", 1, 12)); // NOI18N
        B_register.setText("Register");
        B_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_registerActionPerformed(evt);
            }
        });
        whitePanel.add(B_register);
        B_register.setBounds(55, 881, 79, 31);

        TermsConditions.setFont(new java.awt.Font("Karma", 1, 14)); // NOI18N
        TermsConditions.setForeground(new java.awt.Color(255, 255, 255));
        TermsConditions.setText("I agree to the terms and conditions");
        TermsConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TermsConditionsActionPerformed(evt);
            }
        });
        whitePanel.add(TermsConditions);
        TermsConditions.setBounds(55, 848, 255, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/synergyfinalsproject/newLogo.png"))); // NOI18N
        whitePanel.add(jLabel1);
        jLabel1.setBounds(60, 90, 170, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(whitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(whitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_FirstNameActionPerformed

    }//GEN-LAST:event_TF_FirstNameActionPerformed

    private void TF_MiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_MiddleNameActionPerformed

    }//GEN-LAST:event_TF_MiddleNameActionPerformed

    private void TF_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_YearActionPerformed

    }//GEN-LAST:event_TF_YearActionPerformed

    private void MaritalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaritalStatusActionPerformed

    }//GEN-LAST:event_MaritalStatusActionPerformed

    private void TF_month1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_month1ActionPerformed

    }//GEN-LAST:event_TF_month1ActionPerformed

    private void TF_day1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_day1ActionPerformed

    }//GEN-LAST:event_TF_day1ActionPerformed

    private void TF_surname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_surname2ActionPerformed

    }//GEN-LAST:event_TF_surname2ActionPerformed

    private void Gender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gender2ActionPerformed

    }//GEN-LAST:event_Gender2ActionPerformed

    private void TF_phoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_phoneNumActionPerformed

    }//GEN-LAST:event_TF_phoneNumActionPerformed

    private void TF_Email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Email1ActionPerformed

    }//GEN-LAST:event_TF_Email1ActionPerformed

    private void L_haveAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_haveAccountMouseClicked

        JFrame login = new Synergy_LogIn();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_L_haveAccountMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        // Object to setVisibility and append displayError's specific Messages
        Error_Display errorMSG = new Error_Display();

        /*

        Total amount of Errors to display [9]

        1. Empty TextField Error: if the user did not fill up one of the textfields.
        2. Mismatch Password Error: if the user's password and confirmed password do not match.
        3. Missing Symbol and/or Number Error: a user's password must have atleast 1 number and 1 symbol.
        4. Passowrd Length Error: password's length must be atleast 6 characters long. (this includes the 1 number and 1 symbol rule)
        5. Phone Number Letter and/or Symbol Error: if the user accidentaly included a letter or a symbol in the phone number jTextField.
        6. Phone Number Length Error: user's phone number must be 11 digits to be exact.
        7. Gender Selection Error: A gender must be selected in the jComboBox.
        8. Status Selection Error: A martial status must be selected in the jComboBox.
        9. T&C Unchecked Error: if the user left the terms and condition box unchecked.

         */
        //-------------------------------------------------------------------------------------------
        if (TF_FirstName.getText().isEmpty()) { // [1]

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_MiddleName.getText().isEmpty()) {

            errorMSG.setVisible(true); // ***
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_surname2.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_month1.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_day1.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_Year.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_Email1.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_phoneNum.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_UserName.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_password.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_cPassword.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else if (TF_UserName.getText().isEmpty()) {

            errorMSG.setVisible(true);
            errorMSG.displayError.append(("\nEmpty TextField Error: \nOne or More TextField is Empty."));

        } else {

            if (!TF_password.getText().equals(TF_cPassword.getText())) { // [2]
                errorMSG.setVisible(true);
                errorMSG.displayError.append("Mismatch Password Error: \nPassword and Confirmed Password do NOT match.");

            } else {

                if (!TF_password.getText().matches(".*[a-zA-Z].*") || !TF_password.getText().matches(".*\\d.*") || !TF_password.getText().matches(".*[^a-zA-Z\\d].*")) { // [3]
                    errorMSG.setVisible(true);
                    errorMSG.displayError.append("Missing Symbol and/or Number Error: \nPassword requires atleast ONE Symbol and ONE Number.");

                } else {

                    if (TF_password.getText().length() <= 5) { // [4]
                        errorMSG.setVisible(true);
                        errorMSG.displayError.append("Passowrd Length Error: \nPassword must atleast have 6 characters.");

                    } else {

                        if (TF_phoneNum.getText().matches(".*[a-zA-Z].*") || TF_phoneNum.getText().matches(".*[^\\d].*")) { // [5]
                            errorMSG.setVisible(true);
                            errorMSG.displayError.append("Phone Number Letter and/or Symbol Error: \nPhone Number TextField has a Letter and/or Number in it.");

                        } else {

                            if (TF_phoneNum.getText().length() != 11) { // [6]
                                errorMSG.setVisible(true);
                                errorMSG.displayError.append("Phone Number Length Error: \nPhone Number must have and should be equal to 11 digits.");

                            } else {

                                if (Gender2.getSelectedIndex() == 0) { // [7]

                                    errorMSG.setVisible(true);
                                    errorMSG.displayError.append("Gender Selection Error: \nUser must select a gender from the list.");

                                } else {

                                    if (MaritalStatus.getSelectedIndex() == 0) {

                                        errorMSG.setVisible(true);
                                        errorMSG.displayError.append("Status Selection Error: \nUser must select a martial status from the list.");

                                    } else {

                                        if (!jCheckBox1.isSelected()) {

                                            errorMSG.setVisible(true);
                                            errorMSG.displayError.append("T&C unchecked Error: \nTerms And Condition Must be checked before you can create an account.");

                                        } else {
                                            
                                            dataBaseV2 db = new dataBaseV2();
                                            
                                            String regUsername = TF_UserName.getText();
                                            String regPassword = TF_password.getText();

                                            db.addUserData(regUsername, regPassword);

                                            JFrame login = new Synergy_LogIn();
                                            login.setVisible(true);

                                        }

                                    }

                                }

                            }

                        }

                    }

                }

            }

        }
    }//GEN-LAST:event_registerActionPerformed

    private void B_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_registerActionPerformed

    }//GEN-LAST:event_B_registerActionPerformed

    private void TermsConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TermsConditionsActionPerformed

    }//GEN-LAST:event_TermsConditionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Synergy_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Synergy_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Synergy_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Synergy_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Synergy_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_register;
    private javax.swing.JComboBox<String> Gender2;
    private javax.swing.JLabel L_firstName;
    private javax.swing.JLabel L_firstName1;
    private javax.swing.JLabel L_firstName3;
    private javax.swing.JLabel L_gender;
    private javax.swing.JLabel L_haveAccount;
    private javax.swing.JLabel L_lastName;
    private javax.swing.JLabel L_lastName1;
    private javax.swing.JLabel L_lastName2;
    private javax.swing.JLabel L_lastName3;
    private javax.swing.JLabel L_lastName4;
    private javax.swing.JLabel L_lastName5;
    private javax.swing.JLabel L_lastName6;
    private javax.swing.JLabel L_password;
    private javax.swing.JLabel L_password2;
    private javax.swing.JLabel L_password3;
    private javax.swing.JLabel L_password4;
    private javax.swing.JComboBox<String> MaritalStatus;
    private javax.swing.JTextField TF_Email1;
    private javax.swing.JTextField TF_FirstName;
    private javax.swing.JTextField TF_MiddleName;
    private javax.swing.JTextField TF_UserName;
    private javax.swing.JTextField TF_Year;
    private javax.swing.JTextField TF_address1;
    private javax.swing.JTextField TF_cPassword;
    private javax.swing.JTextField TF_day1;
    private javax.swing.JTextField TF_month1;
    private javax.swing.JTextField TF_password;
    private javax.swing.JTextField TF_phoneNum;
    private javax.swing.JTextField TF_surname2;
    private javax.swing.JCheckBox TermsConditions;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel newBluePanel;
    private javax.swing.JButton register;
    private javax.swing.JLabel title;
    private javax.swing.JPanel whitePanel;
    // End of variables declaration//GEN-END:variables
}
